FROM python:3.6
WORKDIR /code
RUN pip install ipfsapi==0.4.3
RUN pip install flask==1.0.2
RUN pip install pyOpenSSL==19.0.0
RUN pip install pyota==2.0.7
RUN pip install docker==3.7.0
CMD ["/bin/bash"]
